In [2]:
import setup
import numpy as np
import symmetry as s

# smallest set of generators for O_h
S = [[[-1,0,0], [0,1,0], [0,0,1]],
     [[0,0,1], [1,0,0], [0,1,0]],
     [[1,0,0], [0,0,1], [0,1,0]]]
print(len(s.Symmetry.from_generator(S, False)), "= 48")
a = s.Symmetry.from_generator([S[0]], False)
b = s.Symmetry.from_generator([S[1]], False)
c = s.Symmetry.from_generator([S[2]], False)
print(len(a), len(b * c))
print(len(a * (b * c)))
#print(len(s.Symmetry.from_generator((a * b * c).S, True)))

# square symmetries
print(len(s.Symmetry.square()), "= 8")

48 = 48
2 6
48
8 = 8


In [2]:
classes = s.Symmetry.cubic(True).conjugacy_classes()
for c in classes:
    print(len(c), end=", ")

6, 6, 8, 3, 1, 6, 6, 8, 3, 1, 

In [3]:
C_6 = s.Symmetry.from_generator([[[np.exp(2j*np.pi/6)]],], False)
print(len(C_6))
C_3 = s.Symmetry.from_generator([[[np.exp(2j*np.pi/3)]],], False)
print(len(C_3))
C_2 = s.Symmetry.from_generator([[[np.exp(2j*np.pi/2)]],], False)
print(len(C_2))
print((C_6 / C_3) == C_2)

6
3
2
True


In [4]:
# smallest set of generators for O
S = [[[0,1,0], [-1,0,0], [0,0,1]],
     [[0,0,1], [1,0,0], [0,1,0]]]
O = s.Symmetry.from_generator(S, False)
print(len(O), "= 24")
assert s.Symmetry.cubic(False) == O
# generators for a klein four subgroup V_4
S = [[[-1,0,0], [0,-1,0], [0,0,1]],
     [[1,0,0], [0,-1,0], [0,0,-1]]]
V_4 = s.Symmetry.from_generator(S, False)
print(len(V_4), "= 4")
# generators for the factor group ig
S = [[[0,0,1], [0,-1,0], [1,0,0]],
     [[-1,0,0], [0,0,1], [0,1,0]]]
F = s.Symmetry.from_generator(S, False)
print(len(F), "= 6")
assert s.Symmetry.even_perm3(False) == F
assert V_4 * F == O
assert O / V_4 == F
assert O / s.Symmetry.mirror3(False) == F
# perm3 is no normal divisor of the cubic group
#print(O / s.Symmetry.perm3(False) == s.Symmetry.mirror3(False))

24 = 24
4 = 4
6 = 6


In [5]:
# smallest set of generators for O
S = [[[0,1,0], [-1,0,0], [0,0,1]],
     [[0,0,1], [1,0,0], [0,1,0]]]
O = s.Symmetry.from_generator(S, False)
print(len(O), "= 24")

24 = 24


In [10]:
S = [((0, 1), (-1, 0))]
R = s.Symmetry.from_generator(S, False)
print(R.S, R.inversion)

[[[ 1.  0.]
  [ 0.  1.]]

 [[ 0.  1.]
  [-1.  0.]]

 [[-1.  0.]
  [ 0. -1.]]

 [[ 0. -1.]
  [ 1.  0.]]] False


In [12]:
S = [((0, 1), (-1, 0)), ((1, 0), (0, -1))]
Sq = s.Symmetry.from_generator(S, False)
print(Sq.S, Sq.inversion)
print((Sq / R).S)

[[[ 1.  0.]
  [ 0.  1.]]

 [[ 0.  1.]
  [-1.  0.]]

 [[ 1.  0.]
  [ 0. -1.]]

 [[-1.  0.]
  [ 0. -1.]]

 [[ 0. -1.]
  [-1.  0.]]

 [[ 0.  1.]
  [ 1.  0.]]

 [[ 0. -1.]
  [ 1.  0.]]

 [[-1.  0.]
  [ 0.  1.]]] False
[[[ 1.  0.]
  [ 0.  1.]]

 [[-1.  0.]
  [ 0.  1.]]]
